	PROGRAM FCINE

	REAL MASSP,MASST,MASSC,MASSE
	INTEGER*4 ZP,ZT,ZC,ZE,ZR
	INTEGER*4 NP,NT,NC,NE,NR
	INTEGER*4 AP,AT,AC,AE,AR

	CHARACTER NOMEP*6,NOMET*6,NOMEC*6,NOMEE*6,NOMER*6
	CHARACTER NAMNUCL*2

	PARAMETER CCMSEC  = 299792458.		! c in m/sec
	PARAMETER XMNMEV  = 931.502		! Mass(12C)/12 in MeV
	PARAMETER PIGRE   = 3.141592654		! pigreco
	PARAMETER DEGRAD  = 57.29577951		! gradi/radiante
	PARAMETER HBARC   = 197.329		! h(bar)c in MeV*fm
	PARAMETER ESQUARE = 1.440		! e2 in MeV*fm
 
C		  INPUT    REACTION
 
2	WRITE(6,*)
	CALL INP_CH('Projectile',NOMEP)
	CALL NUCLNAM(NOMEP,ZP,AP)
	IF(ZP.LT.0 .OR. AP.LE.0) GOTO 2
	CALL XMASS(ZP,AP,XMASSP,DMASSP)
	MASSP=XMASSP+AP*XMNMEV
 
	CALL INP_CH('Target    ',NOMET)
	CALL NUCLNAM(NOMET,ZT,AT)
	IF(ZT.LT.0 .OR. AT.LE.0) GOTO 2
	CALL XMASS(ZT,AT,XMASST,DMASST)
	MASST=XMASST+AT*XMNMEV
 
	ZC=ZP+ZT
	AC=AP+AT
	CALL XMASS(ZC,AC,XMASSC,DMASSC)
	MASSC=XMASSC+AC*XMNMEV
 
	QVAL=XMASSP+XMASST-XMASSC
	DQVAL=SQRT(DMASSP**2+DMASST**2+DMASSC**2)

	MASSRED=MASSP*MASST/(MASSP+MASST)	! massa ridotta in MeV
	RAGGIO=1.21*(AP**(1/3.)+AT**(1/3.)+1.9)	! in fermi

	BARIN=ESQUARE*ZP*ZT/RAGGIO		! barriera coulombiana in MeV

	WRITE(6,*)
	WRITE(6,'('' Projectile         '',I6,A2,6X,''MASS ='',F10.6,'' AMU'')') AP,NAMNUCL(ZP),MASSP/XMNMEV
	WRITE(6,'('' Target             '',I6,A2,6X,''MASS ='',F10.6,'' AMU'')') AT,NAMNUCL(ZT),MASST/XMNMEV
	WRITE(6,'('' Compound nucleus   '',I6,A2,6X,''MASS ='',F10.6,'' AMU'')') AC,NAMNUCL(ZC),MASSC/XMNMEV

	WRITE(6,'('' Q-value (CM )          = '',F9.3,'' MeV'')') QVAL

	WRITE(6,'('' COULBin (CM )          = '',F9.3,'' MeV'')') BARIN
	WRITE(6,'('' COULBin (LAB)          = '',F9.3,'' MeV'')') BARIN*(1+MASSP/MASST)

	IF(QVAL.LT.0) WRITE(6,'('' THRESHOLD ENERGY (LAB) = '',F9.3,'' MeV'')') -QVAL*(1+MASSP/MASST)

	CALL INP_R1('Projectile Energy (LAB MeV)',EPROJM)
	IF(EPROJM.LE.0) GOTO 2
	EPROJ=EPROJM

	ECM =EPROJ*MASSP/(MASSP+MASST)
	VCM =SQRT(2*ECM/MASSC)*100
	WRITE(6,'('' E   (of CM)  = '',F9.3,'' MeV'')') ECM
	WRITE(6,'('' v/c (of CM)  = '',F9.3,'' %''  )') VCM

	ECAN=EPROJ*MASST/(MASSP+MASST)
	EXENER=ECAN+QVAL
	WRITE(6,'('' Ecan(in CM)  = '',F9.3,'' MeV'')') ECAN
	WRITE(6,'('' Ex  (in CM)  = '',F9.3,'' MeV'')') EXENER

	IF(EXENER.LT.0) GOTO 2
	IF(ECAN.LE.BARIN) GOTO 2

	LMAX=RAGGIO*SQRT(2.*(ECAN-BARIN)*MASSRED)/HBARC	! Lmax in unita' h/
	BMAX=RAGGIO*SQRT((ECAN-BARIN)/ECAN)		! MAXimpact par. in fm
	SFUS=PIGRE*BMAX**2/100.				! Sigma_fus in barn
	WRITE(6,'('' Lmax         ='',I10  ,'' hbar'' )') LMAX
	WRITE(6,'('' Fusion C.S.  ='',F10.0,'' mbarn'')') SFUS*1000

100	CALL INP_CH('Evaporated Particle',NOMEE)
	CALL NUCLNAM(NOMEE,ZE,AE)
	IF(ZE.LT.0 .OR. AE.LE.0) GOTO 2
	CALL XMASS(ZE,AE,XMASSE,DMASSE)
	MASSE=XMASSE+AE*XMNMEV

	ZR=ZC-ZE
	AR=AC-AE
	CALL XMASS(ZR,AR,XMASSR,DMASSR)
	MASSR=XMASSR+AR*XMNMEV

	WRITE(6,'('' Evaporated particle'',I6,A2,6X,''MASS ='',F10.6,'' AMU'')') AE,NAMNUCL(ZE),MASSE/XMNMEV
	WRITE(6,'('' Residuum           '',I6,A2,6X,''MASS ='',F10.6,'' AMU'')') AR,NAMNUCL(ZR),MASSR/XMNMEV

	QVALE=XMASSC-(XMASSR+XMASSE)
	DQVALE=SQRT(DMASSC**2+DMASSR**2+DMASSE**2)
	BAROUT=ZE*ZR/(AR**(1/3.)+AE**(1/3.)+2)

	WRITE(6,'('' Q-value (CM) = '',F9.3,'' MeV'')') QVALE
	IF(ZE.GT.0) WRITE(6,'('' COULBout(CM) = '',F9.3,'' MeV'')') BAROUT

	CALL INP_R1('Ev.Particle Energy (CM MeV)',EEVM)
	IF(EEVM.LE.0) GOTO 2
	EEV=EEVM

	EXENER=EXENER+QVALE-EEV
	WRITE(6,'('' Ex  (in CM)  = '',F9.3,'' MeV'')') EXENER
	IF(EXENER.LT.0) GOTO 2

	AC=AR
	ZC=ZR
	XMASSC=XMASSR
	MASSC=MASSR
	DMASSC=DMASSR
	
	GOTO 100

	END
