	PROGRAM QCINE
 

	REAL MASSP,MASST,MASSD,MASSU
	INTEGER*4 ZP,ZT,ZD,ZU
	INTEGER*4 AP,AT,AD,AU
	CHARACTER NOMEP*6,NOMET*6,NOMED*6
	CHARACTER TESTO*20,NAMNUCL*2
	PARAMETER CMSEC=299792500.
	PARAMETER XMNMEV=931.478
	PARAMETER PIGRE=3.141592654
	PARAMETER DEGRAD=57.29577951

	DATA XSTEP/10./

	logical*1 compound
 
C		  INPUT    REACTION
 
2	WRITE(6,*)
	CALL INP_CH('Projectile        ',NOMEP)
	CALL NUCLNAM(NOMEP,ZP,AP)
	IF(ZP.LT.0 .OR. AP.LE.0) GOTO 2
	CALL XMASS(ZP,AP,XMASSP,DMASSP)
	MASSP=XMASSP+AP*XMNMEV

	CALL INP_CH('Target            ',NOMET)
	CALL NUCLNAM(NOMET,ZT,AT)
	IF(ZT.LT.0 .OR. AT.LE.0) GOTO 2
	CALL XMASS(ZT,AT,XMASST,DMASST)
	MASST=XMASST+AT*XMNMEV
 
	CALL INP_CH('Detected particle ',NOMED)
	lnomed=lengthc(nomed)
	compound=.true.
	if(lnomed.gt.0) then
	  CALL NUCLNAM(NOMED,ZD,AD)
	  IF(ZT.LT.0 .OR. AT.LE.0) GOTO 2
	  if(at.gt.0) compound=.false.
	else
	  zd=zp+zt
	  ad=ap+at
	endif
	MASSD=0
	IF(ZD.NE.0 .OR. AD.NE.0) THEN
	  CALL XMASS(ZD,AD,XMASSD,DMASSD)
	  MASSD=XMASSD+AD*XMNMEV
	ENDIF
 
	ZU=ZP+ZT-ZD
	AU=AP+AT-AD
	IF(ZU.LT.0 .OR. AU.LT.0) GO TO 2
	CALL XMASS(ZU,AU,XMASSU,DMASSU)
	MASSU=XMASSU+AU*XMNMEV
 
	QVAL=(XMASSP+XMASST)-(XMASSD+XMASSU)
	DQVAL=SQRT(DMASSP**2+DMASST**2+DMASSU**2+DMASSD**2)
	BARIN= ZP*ZT/(AP**(1/3.)+AT**(1/3.)+2)
	BAROUT=ZU*ZD/(AU**(1/3.)+AD**(1/3.)+2)

	WRITE(6,*)

	TESTO=' Projectile'
	WRITE(6,10) TESTO,AP,NAMNUCL(ZP),MASSP/XMNMEV
	WRITE(7,10) TESTO,AP,NAMNUCL(ZP),MASSP/XMNMEV

	TESTO=' Target'
	WRITE(6,10) TESTO,AT,NAMNUCL(ZT),MASST/XMNMEV
	WRITE(7,10) TESTO,AT,NAMNUCL(ZT),MASST/XMNMEV

	if(compound) then
	  TESTO=' Compound nucleus'
	  WRITE(6,10) TESTO,AD,NAMNUCL(ZD),MASSD/XMNMEV
	  WRITE(7,10) TESTO,AD,NAMNUCL(ZD),MASSD/XMNMEV

	  WRITE(6,15) QVAL,DQVAL
	  WRITE(7,15) QVAL,DQVAL

	  WRITE(6,17) BARIN,BARIN*(1+MASSP/MASST)
	  WRITE(7,17) BARIN,BARIN*(1+MASSP/MASST)

	  IF(QVAL.LT.0) EMIN=-QVAL*(1+MASSP/MASST)
	  WRITE(6,20) EMIN
	  WRITE(7,20) EMIN

	  goto 2
	endif

	TESTO=' Detected particle'
	WRITE(6,10) TESTO,AD,NAMNUCL(ZD),MASSD/XMNMEV
	WRITE(7,10) TESTO,AD,NAMNUCL(ZD),MASSD/XMNMEV

	TESTO=' RECOIL'
	WRITE(6,10) TESTO,AU,NAMNUCL(ZU),MASSU/XMNMEV
	WRITE(7,10) TESTO,AU,NAMNUCL(ZU),MASSU/XMNMEV

	WRITE(6,15) QVAL,DQVAL
	WRITE(7,15) QVAL,DQVAL

	WRITE(6,17) BARIN,BARIN*(1+MASSP/MASST)
	WRITE(7,17) BARIN,BARIN*(1+MASSP/MASST)

	WRITE(6,18) BAROUT,BAROUT*(1+MASSP/MASST)
	WRITE(7,18) BAROUT,BAROUT*(1+MASSP/MASST)


	CALL INP_R1('Excitation energy (MeV) ',EXENER)
	IF(EXENER.LT.0) GOTO 2

	WRITE(7,'('' Ex= '',F8.1,'' MeV'')') EXENER

	EMIN=0.
	IF((QVAL-EXENER).LT.0) EMIN=-(QVAL-EXENER)*(1+MASSP/MASST)
	WRITE(6,20) EMIN
	WRITE(7,20) EMIN

	CALL INP_R1('Projectile energy (MeV) ',EPROJ)
	IF(EPROJ.LE.0) GOTO 2

	WRITE(7,'('' Projectile energy = '',F9.1,'' MeV'')') EPROJ

	ECAN=EPROJ*MASST/(MASSP+MASST)
	VDCM=SQRT(2*MASSU*MASST*EPROJ/MASSD/(MASSD+MASSU)/(MASSP+MASST)*
	1	(1+QVAL/ECAN))*100
	EDCM=MASSD*(VDCM/100)**2/2
	VCMLAB=SQRT(2*EPROJ*MASSP)/(MASSP+MASST)*100
	VDVCM=VDCM/VCMLAB

	WRITE(6,25) ECAN,EDCM,VDCM,VCMLAB,VDVCM
	WRITE(7,25) ECAN,EDCM,VDCM,VCMLAB,VDVCM

	CALL INP_R1('Ang. Step (DEG.) ',XSTEP)
	IF(XSTEP.LE.0 .OR. XSTEP.GT.180) GOTO 2

	WRITE(6,*)

	DO 100 XI=0,180,XSTEP
	THD=XI/DEGRAD
	CALL CINEMA(MASSP,MASST,MASSD,MASSU,QVAL-EXENER,EPROJ,THD,
	1	ENED1,THU1,ENEU1,ENED2,THU2,ENEU2,THCMD1,THCMD2)

	THD=THD*DEGRAD
	THU1=THU1*DEGRAD
	THU2=THU2*DEGRAD
	THCMD1=THCMD1*DEGRAD
	THCMD2=THCMD2*DEGRAD

	IF(ENED1.LT.0. .AND. ENED2.LT.0.) GOTO 100

	IF(ENED1.GT.0.) THEN
		VD1C=SQRT(2*ENED1/MASSD)*100
		VU1C=SQRT(2*ENEU1/MASSU)*100
		WRITE(6,30) THD,THCMD1,ENED1,VD1C,THU1,ENEU1,VU1C
		WRITE(7,30) THD,THCMD1,ENED1,VD1C,THU1,ENEU1,VU1C
		ENDIF

	IF(ENED2.GT.0. .AND. ENED1.LT.0.) THEN
		VD2C=SQRT(2*ENED2/MASSD)*100
		VU2C=SQRT(2*ENEU2/MASSU)*100
		WRITE(6,30) THD,THCMD2,ENED2,VD2C,THU2,ENEU2,VU2C
		WRITE(7,30) THD,THCMD2,ENED2,VD2C,THU2,ENEU2,VU2C
		ENDIF

	IF(ENED2.GT.0. .AND. ENED1.GT.0.) THEN
		VD2C=SQRT(2*ENED2/MASSD)*100
		VU2C=SQRT(2*ENEU2/MASSU)*100
		WRITE(6,40) THCMD2,ENED2,VD2C,THU2,ENEU2,VU2C
		WRITE(7,40) THCMD2,ENED2,VD2C,THU2,ENEU2,VU2C
		ENDIF

100	CONTINUE

	WRITE(7,'(1H1)')
	GOTO 2


10	FORMAT(A20,I6,A2,10X,'MASS =',F10.6,'  AMU')

15	FORMAT(/' Q-VALUE(C.M.)= ',F12.3,' +- ',F7.3,' MeV')

17	FORMAT(/' COULBin  = ',F9.3,' ( CM )',5X,F9.3,' ( LAB )    MeV')

18	FORMAT( ' COULBout = ',F9.3,' ( CM )',5X,F9.3,' ( LAB )    MeV'/)

20	FORMAT(/' THRESHOLD ENERGY(LAB) = ',F8.3,' MeV'/)

25	FORMAT(/' ECAN        = ',F8.3,' MeV',/
	1	' ED(CM)      = ',F8.3,' MeV   VD(CM)/C = ',F8.3,' %',/
	1	' VCM(LAB)/C  = ',F8.3,' %      VD/VCM  = ',F10.3,//)

30	FORMAT(' THD=',F5.1,'(CM=',F5.1,') ED=',F8.3,'(v/c=',F5.2,'%)',
	1	'    THU=',F5.1,' EU=',F8.3,'(v/c=',F5.2,'%)')

40	FORMAT(T11,         '(CM=',F5.1,') ED=',F8.3,'(v/c=',F5.2,'%)',
	1	'    THU=',F5.1,' EU=',F8.3,'(v/c=',F5.2,'%)')

	END
