	PROGRAM QVALORE
 
	REAL MASSP,MASST,MASSCOMP
	INTEGER*4 ZP,ZT,ZCOMP
	INTEGER*4 AP,AT,ACOMP
	CHARACTER TESTO*20,NAMNUCL*2,NAM*2

	DATA CMSEC/299792500./
	DATA XMNMEV/931.478/
	DATA PIGRE/3.141592654/
	DATA DEGRAD/57.29577951/
 
C		  INPUT    REACTION
 
2	WRITE(6,'(//)')
	CALL inp_i2(' Z, A   OF PROJECTILE   ',ZP,AP)
	IF(ZP.LT.0 .OR. AP.LT.ZP) GO TO 2
	CALL XMASS(ZP,AP,XMASSP,DMASSP)
	MASSP=XMASSP+AP*XMNMEV
 
	CALL inp_i2(' Z, A   OF TARGET       ',ZT,AT)
	IF(ZT.LT.0 .OR. AT.LT.ZT) GO TO 2
	CALL XMASS(ZT,AT,XMASST,DMASST)
	MASST=XMASST+AT*XMNMEV
 
	ZCOMP=ZP+ZT
	ACOMP=AP+AT
	CALL XMASS(ZCOMP,ACOMP,XMASSCOMP,DMASSCOMP)
	MASSCOMP=XMASSCOMP+ACOMP*XMNMEV

	QVAL=(XMASSP+XMASST)-XMASSCOMP
	DQVAL=SQRT(DMASSP**2+DMASST**2+DMASSCOMP**2)
	BARIN= ZP*ZT/(AP**(1/3.)+AT**(1/3.)+2)

	WRITE(6,'(//)')
	TESTO='PROJECTILE'
	NAM='  '
	IF(AP.GT.0) NAM=NAMNUCL(ZP)
	WRITE(6,10) TESTO,AP,NAM,MASSP/XMNMEV
	TESTO='TARGET'
	NAM='  '
	IF(AT.GT.0) NAM=NAMNUCL(ZT)
	WRITE(6,10) TESTO,AT,NAM,MASST/XMNMEV
	TESTO='COMPOUND'
	NAM='  '
	IF(ACOMP.GT.0) NAM=NAMNUCL(ZCOMP)
	WRITE(6,10) TESTO,ACOMP,NAM,MASSCOMP/XMNMEV

	WRITE(6,15) QVAL,DQVAL
	IF(QVAL.LT.0) WRITE(6,20) -QVAL*(1+MASSP/MASST)
	IF(BARIN.NE.0) WRITE(6,25) BARIN,BARIN*(1+MASSP/MASST)

10	FORMAT(1X,A20,I6,A2,10X,'MASS =',F10.6,'  AMU')
15	FORMAT(/' Q-VALORE  ( CM )   = ',F9.3,'(',F6.3,')  MeV')
20	FORMAT( ' ENERGIA DI SOGLIA  = ',F9.3,'   MeV')
25	FORMAT(/' COULBin  = ',F9.3,' ( CM )',5X,F9.3,' ( LAB )    MeV')
35	FORMAT( ' COULBout = ',F9.3,' ( CM )',5X,F9.3,' ( LAB )    MeV')
	END
